services:
  - type: web
    name: taskwave-api
    runtime: docker
    rootDir: taskwave_backend
    plan: free                  # ← 이것이 핵심!
    healthCheckPath: /api/health
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: DATABASE_URL
        fromDatabase:
          name: taskwave-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: STORAGE_BACKEND
        value: local
      - key: MEDIA_ROOT
        value: /app/media

  - type: web
    name: taskwave-app
    runtime: static
    rootDir: taskwave-app
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://taskwave-api.onrender.com
    routes:
      - type: rewrite
        source: /api/:path*
        destination: https://taskwave-api.onrender.com/api/:path*
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: taskwave-db
    plan: free                  # ← DB도 반드시 free로!
