# Auto-generated by Alembic; please adjust!
from alembic import op
import sqlalchemy as sa

revision = '288fb98f9629'
down_revision = 'ecdc6627387a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
