# Auto-generated by Alembic; please adjust!
from alembic import op
import sqlalchemy as sa

revision = '288fb98f9629'
down_revision = 'ecdc6627387a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'date')
    # ### end Alembic commands ###
