# Auto-generated by Alembic; please adjust!
from alembic import op
import sqlalchemy as sa

revision = '5f6ccf9ac4f9'
down_revision = ('b77dff0f9332', 'hotfix01')
branch_labels = None
depends_on = None

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
