"""create all tables

Revision ID: b77dff0f9332
Revises: 
Create Date: 2024-07-23 15:10:35.283025

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b77dff0f9332'
down_revision = None
branch_labels = None
depends_on = None

from app.db.base import Base
from app.models import user, subject, schedule, material, upload, event

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
    # ### end Alembic commands ###