# Auto-generated by Alembic; please adjust!
from alembic import op
import sqlalchemy as sa

revision = 'b77dff0f9332'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
