# Auto-generated by Alembic; please adjust!
from alembic import op
import sqlalchemy as sa

revision = 'ecdc6627387a'
down_revision = '2a15123514a1'
branch_labels = None
depends_on = None

def upgrade() -> None:
    pass

def downgrade() -> None:
    pass
