"""allow null for job timestamps

Revision ID: 3ba129e02b1b
Revises: 1c3d1999c943
Create Date: 2025-06-28 20:38:54.508549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba129e02b1b'
down_revision: Union[str, Sequence[str], None] = '1c3d1999c943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cluster_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('cluster_jobs', 'n_clusters',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cluster_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('cluster_jobs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('cluster_members', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('clusters', 'job_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('clusters', 'label',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clusters', 'centroid',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_clusters_label'), 'clusters', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clusters_label'), table_name='clusters')
    op.alter_column('clusters', 'centroid',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('clusters', 'label',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clusters', 'job_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('cluster_members', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cluster_jobs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('cluster_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('cluster_jobs', 'n_clusters',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cluster_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
