"""add parent id to comments

Revision ID: b511805ae0bc
Revises: 7d98f35f0c29
Create Date: 2025-07-06 17:23:49.613289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b511805ae0bc'
down_revision: Union[str, Sequence[str], None] = '7d98f35f0c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.alter_column('comments', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
