version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: taskwave
      POSTGRES_PASSWORD: taskwave
      POSTGRES_DB: taskwave
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    environment:
      BACKEND_CORS_ORIGINS: '["http://localhost:3000","http://127.0.0.1:3000"]'  # ← 추가
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./media:/app/media

volumes:
  db_data:
